version: '2'

services:
  extractor:
    build: .
    image: keboola/generic-extractor
    volumes:
      - .:/code
      - .tmp:/tmp
    tty: true
    stdin_open: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - .:/code
      - .tmp:/tmp
    command: "/code/phpunit.sh"
    tty: true
    stdin_open: true