version: '2'

services:
  extractor:
    build: .
    image: keboola/generic-extractor
    volumes:
      - .:/home
    working_dir: /home
    entrypoint: "php ./run.php --data=./data"
    tty: true
    stdin_open: true
  tests:
    build: .
    volumes:
      - .:/home
    working_dir: /home
    entrypoint: "./phpunit.sh"
    tty: true
    stdin_open: true