version: '2'

services:
  extractor:
    image: keboola/generic-extractor
    volumes:
      - ./examples/:/examples/
    working_dir: /home
    command: 
      - /bin/sh 
      - -c
      #- "sleep 10000"
      - "php /home/run.php --data=/examples/$$KBC_EXAMPLE_NAME"
    tty: true
    stdin_open: true
