version: '2'

services:
  mock-server:
    container_name: mock-server
    image: quay.io/keboola/ex-generic-mock-server 
    tty: true
    stdin_open: true
    ports:
      - "8888:80"
    volumes:
        - ./examples:/examples/
    environment:
        - KBC_EXAMPLES_DIR=/examples/

  extractor:
    build: ..
    image: keboola/generic-extractor
    volumes:
      - .tmp:/tmp
      - ./examples/:/examples/      
    tty: true
    stdin_open: true
    command:
      - /bin/sh 
      - -c
      - "php /code/run.php --data=/examples/$$KBC_EXAMPLE_NAME"    
    links: 
      - mock-server
