-
    # to be copied from a config file coming with the module (from git)
    class: Keboola\ExGenericModule\FindResponseArray
    level: 100
    type: response
    # config: [...]
#-
    #class: Keboola\ExGenericModule\FilterResponseData
    #level: 200
    #type: response
